"""
01_prepare_data.py — Verify that all required data files exist.

No preprocessing is done here (the feature parquet and splits are already
generated by the upstream pipeline).  This script acts as a fast smoke test
to confirm that the pipeline has everything it needs before training.

Usage:
    python scripts/01_prepare_data.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

# ── Path setup ────────────────────────────────────────────────────────────────
SCRIPTS_DIR = Path(__file__).resolve().parent
PHASE1_ROOT = SCRIPTS_DIR.parent
sys.path.insert(0, str(PHASE1_ROOT / "src"))

from utils import DATA_DIR, SPLITS_DIR, SHARED_DIR   # noqa: E402


def main() -> None:
    print("=" * 62)
    print("01_prepare_data.py — Data Verification")
    print("=" * 62)

    required: list[tuple[str, Path]] = [
        ("Feature parquet",        DATA_DIR   / "lipid_ms2_features.parquet"),
        ("Train split",            SPLITS_DIR / "split_train.npy"),
        ("Val split",              SPLITS_DIR / "split_val.npy"),
        ("Test split",             SPLITS_DIR / "split_test.npy"),
        ("Class encoder",          SHARED_DIR / "class_encoder.joblib"),
        ("Adduct encoder",         SHARED_DIR / "adduct_encoder.joblib"),
        ("Class-to-numchain JSON", SHARED_DIR / "class_to_numchain.json"),
        ("Backbone masses JSON",   SHARED_DIR / "class_backbone_masses.json"),
        ("Precursor mz stats",     SHARED_DIR / "precursor_mz_stats.npy"),
    ]

    all_ok = True
    for desc, path in required:
        status = "OK" if path.exists() else "MISSING"
        if not path.exists():
            all_ok = False
        print(f"  [{status}] {desc}")
        print(f"        {path}")

    if not all_ok:
        print("\n[ERROR] Some required files are missing.")
        print("Run the upstream data preparation pipeline first.")
        sys.exit(1)

    # ── Print summary stats ───────────────────────────────────────────────────
    print("\n── Summary ─────────────────────────────────────────────")
    feat_path = DATA_DIR / "lipid_ms2_features.parquet"
    df = pd.read_parquet(feat_path, engine="pyarrow", columns=["class_enc", "adduct_enc"])
    print(f"  Rows              : {len(df):,}")
    print(f"  Unique classes    : {df['class_enc'].nunique()}")
    print(f"  Unique adducts    : {df['adduct_enc'].nunique()}")

    for split_name in ("train", "val", "test"):
        idx = np.load(SPLITS_DIR / f"split_{split_name}.npy")
        print(f"  {split_name:<5} split size : {len(idx):,}")

    print("\n[OK] All data files present and verified.")


if __name__ == "__main__":
    main()
